[package]
name = "schreme"
version = "0.1.0"
authors = ["jacremer <jacremer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "schreme"
path = "bin/main.rs"
